# Generated by Django 2.0.3 on 2020-10-19 13:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_details', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Aboutus',
                'verbose_name_plural': 'Aboutus',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('ordering', models.IntegerField(default=0)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'catagory',
                'verbose_name_plural': 'catagories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_details', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pri_details', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Privacy',
                'verbose_name_plural': 'Privacy',
            },
        ),
        migrations.CreateModel(
            name='SeoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_meta_title', models.TextField(blank=True)),
                ('index_meta_description', models.TextField(blank=True)),
                ('index_meta_keywords', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seo Content',
                'verbose_name_plural': 'Seo Contentes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_url', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('images', models.FileField(upload_to='service_images/')),
                ('image_alt_tag', models.CharField(blank=True, max_length=200)),
                ('details', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
                ('ordering', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_details', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Term',
            },
        ),
    ]
